services:
  backend-prod:
    image: has21/24ifr:latest
    container_name: 24ifr-backend-prod
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env.prod

  backend-test:
    image: has21/24ifr:testing
    container_name: 24ifr-backend-test
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - .env.test
