import React, { useState, useEffect } from 'react';
import { loadUserSettings, saveUserSettings } from '../services/api';

const ConfigPage = () => {
    const [template, setTemplate] = useState('');
    const [saved, setSaved] = useState(false);

    useEffect(() => {
        const settings = loadUserSettings();
        if (settings && settings.clearanceTemplate) {
            setTemplate(settings.clearanceTemplate);
        } else {
            setTemplate("{CALLSIGN}, {ATC_STATION}, good day. Startup approved. Information {ATIS} is correct. Cleared to {DESTINATION} via {ROUTE}, runway {RUNWAY}. Initial climb {INITIAL_ALT}FT, expect further climb to Flight Level {FLIGHT_LEVEL}. Squawk {SQUAWK}.");
        }
    }, []);

    const handleSave = () => {
        saveUserSettings({ clearanceTemplate: template });
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
    };

    const handleReset = () => {
        const defaultTemplate = "{CALLSIGN}, {ATC_STATION}, good day. Startup approved. Information {ATIS} is correct. Cleared to {DESTINATION} via {ROUTE}, runway {RUNWAY}. Initial climb {INITIAL_ALT}FT, expect further climb to Flight Level {FLIGHT_LEVEL}. Squawk {SQUAWK}.";
        setTemplate(defaultTemplate);
        saveUserSettings({ clearanceTemplate: defaultTemplate });
    };

    return (
        <main className="flex-1 overflow-y-auto p-4 md:p-6 lg:p-8 space-y-8 pt-20 lg:pt-8">
            <header>
                <h1 className="font-display text-3xl font-bold text-white mb-2 uppercase tracking-wide">Advanced Config</h1>
                <p className="text-zinc-500">Customize your clearance generation template.</p>
            </header>

            <div className="bg-surface-dark border border-border-dark rounded-lg p-6 shadow-sm">
                <div className="mb-6">
                    <h2 className="font-display text-lg font-bold text-white tracking-wide uppercase mb-4">Clearance Template</h2>
                    <p className="text-sm text-zinc-400 mb-4">
                        Use the variables below to customize the phraseology generated by the system.
                    </p>

                    <div className="flex flex-wrap gap-2 mb-4">
                        {['{CALLSIGN}', '{ATC_STATION}', '{ATIS}', '{DESTINATION}', '{ROUTE}', '{RUNWAY}', '{INITIAL_ALT}', '{FLIGHT_LEVEL}', '{SQUAWK}'].map(variable => (
                            <button
                                key={variable}
                                onClick={() => setTemplate(prev => prev + ' ' + variable)}
                                className="bg-zinc-900 hover:bg-zinc-800 text-primary text-xs font-mono px-2 py-1 rounded border border-zinc-800 transition-colors"
                            >
                                {variable}
                            </button>
                        ))}
                    </div>

                    <textarea
                        value={template}
                        onChange={(e) => setTemplate(e.target.value)}
                        className="w-full h-32 bg-black/50 border border-zinc-800 text-white font-mono text-sm rounded-lg p-4 outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-4 resize-none"
                        placeholder="Enter your clearance template..."
                    ></textarea>

                    <div className="flex items-center gap-4">
                        <button
                            onClick={handleSave}
                            className="bg-primary hover:bg-primary-dim text-black font-bold uppercase tracking-widest py-2 px-6 rounded transition-all text-sm shadow-[0_0_0_1px_rgba(250,204,21,0.1)] hover:shadow-[0_0_20px_rgba(250,204,21,0.4)] flex items-center gap-2"
                        >
                            <span className="material-symbols-outlined text-lg">save</span>
                            Save
                        </button>
                        <button
                            onClick={handleReset}
                            className="text-zinc-500 hover:text-white px-4 py-2 text-sm uppercase tracking-wider font-bold transition-colors"
                        >
                            Reset to Default
                        </button>
                        {saved && <span className="text-green-500 text-sm font-bold flex items-center gap-1 animate-fadeIn"><span className="material-symbols-outlined text-lg">check</span> Saved!</span>}
                    </div>
                </div>
            </div>
        </main>
    );
};

export default ConfigPage;
