import React, { useState, useEffect } from 'react';
import { loadUserSettings, saveUserSettings, updateUserSettings } from '../services/api';
import { DEFAULT_CLEARANCE_SETTINGS, DEFAULT_CLEARANCE_TEMPLATE, CLEARANCE_PLACEHOLDERS, normalizeSettings } from '../services/clearance';

const ConfigPage = () => {
    const [settings, setSettings] = useState(DEFAULT_CLEARANCE_SETTINGS);
    const [saved, setSaved] = useState(false);

    useEffect(() => {
        const storedSettings = normalizeSettings(loadUserSettings() || {});
        setSettings(storedSettings);
    }, []);

    const handleSave = () => {
        saveUserSettings(settings);
        setSaved(true);
        setTimeout(() => setSaved(false), 2000);
    };

    const handleReset = () => {
        setSettings(DEFAULT_CLEARANCE_SETTINGS);
        saveUserSettings(DEFAULT_CLEARANCE_SETTINGS);
    };

    const updateSetting = (key, value) => {
        setSettings(prev => ({ ...prev, [key]: value }));
    };

    const handleInlineSave = (key, value) => {
        updateSetting(key, value);
        updateUserSettings({ [key]: value });
    };

    return (
        <main className="flex-1 overflow-y-auto p-4 md:p-6 lg:p-8 space-y-8 pt-20 lg:pt-8">
            <header>
                <h1 className="font-display text-3xl font-bold text-white mb-2 uppercase tracking-wide">Advanced Config</h1>
                <p className="text-zinc-500">Customize your clearance generation template.</p>
            </header>

            <div className="bg-surface-dark border border-border-dark rounded-lg p-6 shadow-sm">
                <div className="mb-6">
                    <h2 className="font-display text-lg font-bold text-white tracking-wide uppercase mb-4">Clearance Template</h2>
                    <p className="text-sm text-zinc-400 mb-4">
                        Use the variables below to customize the phraseology generated by the system.
                    </p>

                    <div className="flex flex-wrap gap-2 mb-4">
                        {CLEARANCE_PLACEHOLDERS.map(variable => (
                            <button
                                key={variable}
                                onClick={() => updateSetting('clearanceTemplate', `${settings.clearanceTemplate || DEFAULT_CLEARANCE_TEMPLATE} ${variable}`.trim())}
                                className="bg-zinc-900 hover:bg-zinc-800 text-primary text-xs font-mono px-2 py-1 rounded border border-zinc-800 transition-colors"
                            >
                                {variable}
                            </button>
                        ))}
                    </div>

                    <textarea
                        value={settings.clearanceTemplate}
                        onChange={(e) => updateSetting('clearanceTemplate', e.target.value)}
                        className="w-full h-32 bg-black/50 border border-zinc-800 text-white font-mono text-sm rounded-lg p-4 outline-none focus:border-primary focus:ring-1 focus:ring-primary mb-4 resize-none"
                        placeholder="Enter your clearance template..."
                    ></textarea>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                        <label className="space-y-1.5">
                            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-wider">Default ATC Station</span>
                            <input
                                type="text"
                                value={settings.defaultAtcStation}
                                onChange={(e) => handleInlineSave('defaultAtcStation', e.target.value)}
                                className="w-full bg-black/50 border border-zinc-800 text-white text-sm rounded px-3 py-2.5 outline-none focus:border-primary focus:ring-1 focus:ring-primary"
                                placeholder="IRCC_CTR"
                            />
                        </label>
                        <label className="space-y-1.5">
                            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-wider">Default ATIS Letter</span>
                            <select
                                value={settings.defaultAtisLetter}
                                onChange={(e) => handleInlineSave('defaultAtisLetter', e.target.value)}
                                className="w-full bg-black/50 border border-zinc-800 text-white text-sm rounded px-3 py-2.5 outline-none focus:border-primary focus:ring-1 focus:ring-primary"
                            >
                                {Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)).map(letter => (
                                    <option key={letter} value={letter}>{letter}</option>
                                ))}
                            </select>
                        </label>
                        <label className="space-y-1.5">
                            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-wider">Default Initial Climb</span>
                            <input
                                type="text"
                                value={settings.defaultInitialClimb}
                                onChange={(e) => handleInlineSave('defaultInitialClimb', e.target.value)}
                                className="w-full bg-black/50 border border-zinc-800 text-white text-sm rounded px-3 py-2.5 outline-none focus:border-primary focus:ring-1 focus:ring-primary"
                                placeholder="5000"
                            />
                        </label>
                        <label className="space-y-1.5">
                            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-wider">Default Runway</span>
                            <input
                                type="text"
                                value={settings.defaultRunway}
                                onChange={(e) => handleInlineSave('defaultRunway', e.target.value)}
                                className="w-full bg-black/50 border border-zinc-800 text-white text-sm rounded px-3 py-2.5 outline-none focus:border-primary focus:ring-1 focus:ring-primary"
                                placeholder="27L"
                            />
                        </label>
                        <label className="space-y-1.5">
                            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-wider">Default Routing</span>
                            <select
                                value={settings.defaultRouting}
                                onChange={(e) => handleInlineSave('defaultRouting', e.target.value)}
                                className="w-full bg-black/50 border border-zinc-800 text-white text-sm rounded px-3 py-2.5 outline-none focus:border-primary focus:ring-1 focus:ring-primary"
                            >
                                <option value="As Filed">Use original filed route</option>
                                <option value="SID">SID (Standard Instrument Departure)</option>
                                <option value="VECTORS">Radar Vectors (Controller guidance)</option>
                                <option value="DIRECT">Direct (Navigation to specific waypoint)</option>
                            </select>
                        </label>
                        <label className="space-y-1.5">
                            <span className="text-[10px] font-bold text-zinc-500 uppercase tracking-wider">Default Route Details</span>
                            <input
                                type="text"
                                value={settings.defaultRoutingDetails}
                                onChange={(e) => handleInlineSave('defaultRoutingDetails', e.target.value)}
                                className="w-full bg-black/50 border border-zinc-800 text-white text-sm rounded px-3 py-2.5 outline-none focus:border-primary focus:ring-1 focus:ring-primary"
                                placeholder="MID5J / Fly heading 270 / BPK"
                            />
                        </label>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                        <label className="flex items-center gap-3 bg-black/30 border border-zinc-800 rounded px-4 py-3">
                            <input
                                type="checkbox"
                                checked={settings.uppercaseCallsign}
                                onChange={(e) => handleInlineSave('uppercaseCallsign', e.target.checked)}
                                className="h-4 w-4 accent-primary"
                            />
                            <span className="text-sm text-zinc-300">Uppercase callsign</span>
                        </label>
                        <label className="flex items-center gap-3 bg-black/30 border border-zinc-800 rounded px-4 py-3">
                            <input
                                type="checkbox"
                                checked={settings.autoCopyClearance}
                                onChange={(e) => handleInlineSave('autoCopyClearance', e.target.checked)}
                                className="h-4 w-4 accent-primary"
                            />
                            <span className="text-sm text-zinc-300">Auto-copy generated clearance</span>
                        </label>
                        <label className="flex items-center gap-3 bg-black/30 border border-zinc-800 rounded px-4 py-3">
                            <input
                                type="checkbox"
                                checked={settings.useFiledRouteFallback}
                                onChange={(e) => handleInlineSave('useFiledRouteFallback', e.target.checked)}
                                className="h-4 w-4 accent-primary"
                            />
                            <span className="text-sm text-zinc-300">Use filed route fallback</span>
                        </label>
                    </div>

                    <div className="flex items-center gap-4">
                        <button
                            onClick={handleSave}
                            className="bg-primary hover:bg-primary-dim text-black font-bold uppercase tracking-widest py-2 px-6 rounded transition-all text-sm shadow-[0_0_0_1px_rgba(250,204,21,0.1)] hover:shadow-[0_0_20px_rgba(250,204,21,0.4)] flex items-center gap-2"
                        >
                            <span className="material-symbols-outlined text-lg">save</span>
                            Save
                        </button>
                        <button
                            onClick={handleReset}
                            className="text-zinc-500 hover:text-white px-4 py-2 text-sm uppercase tracking-wider font-bold transition-colors"
                        >
                            Reset to Default
                        </button>
                        {saved && <span className="text-green-500 text-sm font-bold flex items-center gap-1 animate-fadeIn"><span className="material-symbols-outlined text-lg">check</span> Saved!</span>}
                    </div>
                </div>
            </div>
        </main>
    );
};

export default ConfigPage;
